const SCENE_COUNT = 11;

const WebGLMacros = {AMC_ATTRIBUTE_VERTEX : 0,
					 AMC_ATTRIBUTE_COLOR : 1,
					 AMC_ATTRIBUTE_NORMAL : 2,
					 AMC_ATTRIBUTE_TEXTURE0 : 3,
					 AMC_ATTRIBUTE_INSTANCE_VEC0 : 5,
					 AMC_ATTRIBUTE_INSTANCE_VEC1 : 6,
					 AMC_ATTRIBUTE_INSTANCE_VEC2 : 7,
					 AMC_ATTRIBUTE_INSTANCE_VEC3 : 8,
				 	};
