const SCENE_COUNT = 8;

const WebGLMacros = {AMC_ATTRIBUTE_VERTEX : 0,
					 AMC_ATTRIBUTE_COLOR : 1,
					 AMC_ATTRIBUTE_NORMAL : 2,
					 AMC_ATTRIBUTE_TEXTURE0 : 3,
					 AMC_ATTRIBUTE_INSTANCE_VEC0 : 4,
					 AMC_ATTRIBUTE_INSTANCE_VEC1 : 5,
					 AMC_ATTRIBUTE_INSTANCE_VEC2 : 6,
					 AMC_ATTRIBUTE_INSTANCE_VEC3 : 7,
				 	};
